export const LOAD_RECEIPTS_REQUEST = 'LOAD_RECEIPTS_REQUEST';
export const LOAD_RECEIPTS_SUCCESS = 'LOAD_RECEIPTS_SUCCESS';
export const LOAD_RECEIPTS_FAILURE = 'LOAD_RECEIPTS_FAILURE';

export const ADD_RECEIPT_REQUEST = 'ADD_RECEIPT_REQUEST';
export const ADD_RECEIPT_SUCCESS = 'ADD_RECEIPT_SUCCESS';
export const ADD_RECEIPT_FAILURE = 'ADD_RECEIPT_FAILURE';

export const EDIT_RECEIPT_REQUEST = 'EDIT_RECEIPT_REQUEST';
export const EDIT_RECEIPT_SUCCESS = 'EDIT_RECEIPT_SUCCESS';
export const EDIT_RECEIPT_FAILURE = 'EDIT_RECEIPT_FAILURE';

export const DELETE_RECEIPT_REQUEST = 'DELETE_RECEIPT_REQUEST';
export const DELETE_RECEIPT_SUCCESS = 'DELETE_RECEIPT_SUCCESS';
export const DELETE_RECEIPT_FAILURE = 'DELETE_RECEIPT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_USER_ID = 'SET_USER_ID';
